---
version: 3

images:
  base_image:
    name: registry.fedoraproject.org/fedora:40

dependencies:
  python_interpreter:
    package_system: python312
    python_path: /usr/bin/python3.12

  ansible_core:
    package_pip: ansible-core

  ansible_runner:
    package_pip: ansible-runner

  galaxy: requirements.yml

  python: requirements.txt