network:
  ethernets:
    eth1:
      optional: true
    eth2:
      optional: true
  bonds:
    bond0:
      interfaces: [eth1, eth2]
      mtu: 9000
      parameters:
        mode: 802.3ad
  vlans:
    vlan11:
      id: 11
      link: bond0
      dhcp4: false
      addresses: [10.10.11.10/24]
      routes:
        - to: 10.10.12.0/24
          via: 10.10.11.1
    vlan21:
      id: 21
      link: bond0
      dhcp4: false
      addresses: [10.10.21.10/24]
      routes:
        - to: 10.10.22.0/24
          via: 10.10.21.1
    # vlan100:
    #   id: 100
    #   link: bond0
    #   dhcp4: false
    #   addresses: [10.10.100.101/24]
    # vlan101:
    #   id: 101
    #   link: bond0
    #   dhcp4: false
    #   addresses: [10.10.101.101/24]
