---
version: 3

images:
  base_image:
    name: quay.io/centos/centos:stream9

dependencies:
  python_interpreter:
      package_system: "python3.12"
      python_path: "/usr/bin/python3.12"
  ansible_core:
    package_pip: ansible-core
  ansible_runner:
    package_pip: ansible-runner
  galaxy:
    collections:
      - name: arista.avd
        version: 5.4.0
      - name: ansible.scm
        version: 3.0.0

additional_build_files:
    - src: ansible.cfg
      dest: configs

additional_build_steps:
    prepend_final:
        - RUN /usr/bin/dnf -y swap curl-minimal curl
        - COPY _build/configs/ansible.cfg /etc/ansible/ansible.cfg

options:
    package_manager_path: /usr/bin/dnf