---
- name: Update Arista Fabric Configuration
  hosts: all
  connection: local
  gather_facts: false
  collections:
    - arista.avd
  tasks:

    - name: Generate AVD Structured Configurations
      import_role:
        name: eos_designs

    - name: Generate Device Configurations and Documentation
      import_role:
        name: eos_cli_config_gen

    - name: Print the gateway for each host when defined
      ansible.builtin.debug:
        msg: Token is {{ ansible_password }}

    - name: Deploy Configurations and tags to CloudVision
      import_role:
        name: cv_deploy
      vars:
        cv_server: www.arista.io
        cv_token: '{{ ansible_password }}'
