name: Save ANTA report

on:
  push:
    branches:
      - main
    paths:
      - 'artifacts/reports/**'

jobs:
  save-report:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Generate artifact name
      id: generate-name
      run: echo "artifact=${{ github.event.repository.name }}_ANTA-report_$(date +'%Y-%m-%d_%H.%M.%S')" >> $GITHUB_OUTPUT
    - name: Save artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.generate-name.outputs.artifact }}
        path: |
          artifacts/reports/
    - name: Save summary
      run: |
        cat artifacts/reports/*-state.md >> $GITHUB_STEP_SUMMARY